#!/usr/bin/env php
<?php

/**
 * @file
 * Warms the Drupal page cache.
 */

chdir(dirname(__DIR__) . '/web');
$_SERVER['HTTP_USER_AGENT'] = 'Drupal Forge';
$_SERVER['REQUEST_URI'] = $argv[1] ?? '/';
$_SERVER['SCRIPT_NAME'] = '/index.php';
$_SERVER['SERVER_NAME'] = 'localhost';
$_SERVER['SERVER_PORT'] = '80';
ob_start(fn($buffer, $phase) => TRUE, 1);
require 'index.php';
ob_end_clean();
echo "Warmed cache for " . $_SERVER['REQUEST_URI'] . "\n";
