type: drupal11
docroot: web
php_version: "8.5"
webserver_type: apache-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mysql
    version: "8.0"
hooks:
    post-start:
        # Set up debugging.
        - exec: test -f .vscode/launch.json || mkdir -p .vscode && cp .ddev/launch.json .vscode/
        # Run initial setup tasks.
        - exec: .devpanel/init.sh
use_dns_when_possible: true
composer_version: "2"
disable_settings_management: true
web_environment:
    # Set up DevPanel variables.
    - APP_ROOT=$DDEV_COMPOSER_ROOT
    - DRUSH_OPTIONS_URI=$DDEV_PRIMARY_URL
    - WEB_ROOT=$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT
    - DB_HOST=db
    - DB_PORT=3306
    - DB_USER=db
    - DB_PASSWORD=db
    - DB_NAME=db
    - DP_APP_ID=provus_edu
    - DB_DRIVER=mysql
    - COMPOSER_HOME=/home/www/.config/composer
    - DP_AI_VIRTUAL_KEY=
corepack_enable: false
